"Plotting functions to extend with `DNCSMakieRasterExt`"
function animate_2D_field end
function visualise_initial_conditions end
function visualise_initial_stepchange end
function initial_tracer_heaviside end
function visualise_initial_density end
function visualise_snapshot end
